export const theme = {
  light: {
    background: '#ffffff',
    foreground: '#0a0a0a',
    card: '#ffffff',
    cardForeground: '#0a0a0a',
    popover: '#ffffff',
    popoverForeground: '#0a0a0a',
    primary: '#0a0a0a',
    primaryForeground: '#fafafa',
    secondary: '#f4f4f5',
    secondaryForeground: '#0a0a0a',
    muted: '#f4f4f5',
    mutedForeground: '#71717a',
    accent: '#f4f4f5',
    accentForeground: '#0a0a0a',
    destructive: '#ef4444',
    destructiveForeground: '#fafafa',
    border: '#e4e4e7',
    input: '#e4e4e7',
    ring: '#0a0a0a',
    radius: '0.5rem',
  },
  dark: {
    background: '#000000',
    foreground: '#fafafa',
    card: '#0a0a0a',
    cardForeground: '#fafafa',
    popover: '#0a0a0a',
    popoverForeground: '#fafafa',
    primary: '#fafafa',
    primaryForeground: '#0a0a0a',
    secondary: '#1a1a1a',
    secondaryForeground: '#fafafa',
    muted: '#1a1a1a',
    mutedForeground: '#a1a1aa',
    accent: '#1a1a1a',
    accentForeground: '#fafafa',
    destructive: '#ef4444',
    destructiveForeground: '#fafafa',
    border: '#27272a',
    input: '#27272a',
    ring: '#d4d4d8',
    radius: '0.5rem',
  },
} as const;

export type Theme = keyof typeof theme;
export type ThemeColors = typeof theme.light;